# Generated by Django 3.2.3 on 2021-05-13 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogPosts', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_posts', through='blogPosts.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
